export const CREATE_NEW_BOARD = "CREATE_NEW_BOARD";
export const CANCLE_NEW_BOARD = "CANCLE_NEW_BOARD";
export const SUBMIT_NEW_BOARD = "SUBMIT_NEW_BOARD";
export const STORE_NEW_BOARD_TO_COLLECTION = 'STORE_NEW_BOARD_TO_COLLECTION';
export const SUBMIT_NEW_CARD = "SUBMIT_NEW_CARD"
export const SUBMIT_LIST = "SUBMIT_LIST"
export const SELECT_ACTIVE_BOARD = "SELECT_ACTIVE_BOARD"
export const ARCHIVE_POST = "ARCHIVE_POST"