export const CREATE_NEW_BOARD = "CREATE_NEW_BOARD";
export const CANCLE_NEW_BOARD = "CANCLE_NEW_BOARD";
export const SUBMIT_NEW_BOARD = "SUBMIT_NEW_BOARD";
export const STORE_NEW_BOARD_TO_COLLECTION = 'STORE_NEW_BOARD_TO_COLLECTION';